### ISSUE TITLE
Option for changing button text without replacing template

### ISSUE THREAD

**Issue by dlwhiteman** [m-e-conroy/angular-dialog-service#126] opened 2015-07-06 13:56 UTC
Hi, it would be nice to be able to pass in options for the button text without having to replace the entire template for a dialog.  For example, I would like to pass in options to replace the buttons for the confirm dialog to be whatever the action is that I am wanting to perform and Cancel.  If I had "Reformat hard drive?" as my prompt message, it would be more clear if I could pass in "Reformat" and "Cancel" as the button text to replace the default Yes and No.

**Comment by niemyjski** [comment] 2015-07-09 14:26
Do you want to create a pull request for this and we can talk about this more?

**Comment by dlwhiteman** [comment] 2015-07-09 14:37
I'm sorry, I am new to the process of creating a pull request, etc.  Does creating a pull request mean that I am making a commitment to implement the change?  Please feel free to link me to any material that describes the process for Github projects.  All of my Git work so far has been internal to my company. Thanks!

**Comment by niemyjski** [comment] 2015-07-09 14:39
Not necessarily a commitment but it does get it implemented quicker if it's implemented and everyone likes it :). I don't really have any material other than forking it and then doing a pull request via github.com ( https://help.github.com/articles/fork-a-repo/)

**Comment by dougmoscrop** [comment] 2015-07-09 15:06
In other words, @dlwhiteman - writing (at least some) code happens before the pull request is opened.

**Comment by miszou** [comment] 2015-07-17 13:23
Isn't this a duplicate of #66 so therefore can be closed or at least referenced?

**Comment by ckelley7** [comment] 2016-10-10 17:58
Looks like we just need a couple more angular.dialogservice.IDialogOptions that can be used to override the YES and NO button text respectively.

**Comment by mcaden** [comment] 2017-12-08 22:52
I've created a pull request for this feature. It's working in both the translate and the translate-substitution examples. I've also referenced #66 on the PR.

**Comment by niemyjski** [comment] 2018-01-11 15:52
Thanks for the PR @mcaden . Can someone else here review the PR.

**Comment by mcaden** [comment] 2018-03-14 16:37
I believe this can now be closed

**Comment by niemyjski** [comment] 2018-03-15 11:52
Thanks!

**Closed by niemyjski** 2018-03-15 11:52 UTC
Labels: enhancement
