### ISSUE TITLE
Black background with Bootstrap 3.3.4 

### ISSUE THREAD

**Issue by jcstritt** [m-e-conroy/angular-dialog-service#111] opened 2015-03-31 15:15 UTC
Hello. It seems that there is now a bug when using angular-dialogs with bootstrap 3.3.4. The background is no more transparent but black.

**Comment by niemyjski** [comment] 2015-06-11 13:26
@jcstritt were you able to figure out what was causing this behavior? I haven't had a chance to reproduce this yet.

**Comment by m-e-conroy** [comment] 2015-06-11 15:22
@jcstritt @niemyjski I'm currently using Bootstrap 3.3.4, Angular 1.4, Angular-Bootstrap 0.13.0 and Angular-Dialog-Service 5.2.8 and have not experienced this problem.  Sounds like there's an errant CSS statment somewhere.

**Comment by niemyjski** [comment] 2015-06-11 15:26
I was just thinking the same thing as I haven't seen this either.. I
think it's safe to close this issue as I haven't seen it either (but
I'm on latest 1.3).

On 6/11/15, Michael E Conroy <notifications@github.com> wrote:
> @jcstritt @niemyjski I'm currently using Bootstrap 3.3.4, Angular 1.4,
> Angular-Bootstrap 0.13.0 and Angular-Dialog-Service 5.2.8 and have not
> experienced this problem.  Sounds like there's an errant CSS statment
> somewhere.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/m-e-conroy/angular-dialog-service/issues/111#issuecomment-111171323


-- 
Thanks
-Blake Niemyjski

**Comment by m-e-conroy** [comment] 2015-07-10 15:07
Closing this as I cannot reproduce this problem.  My thinking is that there is some CSS class getting in the way of Bootstrap's class

**Closed by m-e-conroy** 2015-07-10 15:07 UTC
Labels: bug
